### ISSUE TITLE
Creating Bed12 file - Use of NBIS tool?

### ISSUE THREAD

**Issue by Juke34** [NBISweden/workshop-RNAseq#3]
In the RseQC step you run 
```
 gtfToGenePred \
   references/annotations/Mus_musculus.GRCm38.101.gtf \
   references/annotations/Mus_musculus.GRCm38.101.genePred

 genePredToBed \
   references/annotations/Mus_musculus.GRCm38.101.genePred\
   references/annotations/Mus_musculus.GRCm38.101.bed
```
while it can be done in one step using AGAT  developed by NBIS (available in conda and docker):
 `agat_convert_sp_gff2bed.pl --gff Mus_musculus.GRCm38.101.gtf  -o Mus_musculus.GRCm38.101.bed`

If the result works as good it should be prefered, isn't it?

See here for more info: https://github.com/NBISweden/GAAS/blob/master/annotation/knowledge/gff_to_bed.md

**Comment by royfrancis** [comment]
I don't think there is a lot of benefit in adding a whole new dependency just for this one step.

**Comment by Juke34** [comment]
For sure the benefit is really limited ^^
